<%--
  Created by IntelliJ IDEA.
  User: claudiudiaconeasa
  Date: 04/12/2019
  Time: 16:10
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Sergey Pozhilov (GetTemplate.com)">

    <title>About the project</title>
    <%--BootStrap from Magister--%>
    <link href="https://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <%--Bootstrap fonts--%>
    <link href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Wire+One' rel='stylesheet' type='text/css'>

    <%-- Css--%>
    <link rel="stylesheet" href="template/css/magister.css">
    <link rel="stylesheet" href="template/css/mycss.css"

<%--    /////////////////////////////////////////////////////////////--%>

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->

    <link href="https://fonts.googleapis.com/css?family=Oleo+Script:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Teko:400,700" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

</head>

<body class="theme-invert">
<section id="contact">

    <div class="section-content">
        <h1 class="section-header"><span class="content-header wow fadeIn " data-wow-delay="0.2s" data-wow-duration="2s">Contact</span></h1>
        <h3>Any questions and suggestions for improvement?</h3>
    </div>
    <div class="contact-section">
    <div class="container">

<%--        <h2 class="text-center title">About Engaging History Tools</h2>--%>
<%--        <div class = "row" style ="position:absolute">--%>
<%--            <div class="col-sm-4 col-sm-offset-2">--%>
<%--            <h5><strong>What's the utility of this project?<br></strong></h5>--%>
<%--            <p>Students across all academic years will get the chance to explore in depth about the University they're studying at and the City of Manchester in terms of the cultural past events.</p>--%>
<%--        </div>--%>
<%--        <div class="col-sm-4">--%>
<%--            <h5><strong>TimeMap and Calendar enagagement<br></strong></h5>--%>
<%--            <p>By creating a nice looking physical calendar which is also aimed to get generated by yourself, a simple QR code scan would point you to an article with more information and a chronology of all the events. Pictures are assigned based on each month of an year and hope this will make you curious to open it up and explore.</p>--%>
<%--        </div>--%>
<%--    </div>--%>

    <form>
        <div class="col-md-6 form-line">
            <div class="form-group">
                <label for="exampleInputUsername">Your name</label>
                <input type="text" class="form-control" id="" placeholder=" Enter Name">
            </div>
            <div class="form-group">
                <label for="exampleInputEmail">Email Address</label>
                <input type="email" class="form-control" id="exampleInputEmail" placeholder=" Enter Email id">
            </div>
            <div class="form-group">
                <label for="telephone">Mobile No.</label>
                <input type="tel" class="form-control" id="telephone" placeholder=" Enter 10-digit mobile no.">
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for ="description"> Message</label>
                <textarea  rows="7" cols="7" class="form-control" id="description" placeholder="Enter Your Message"></textarea>
            </div>
            <div>

                <button type="button" class="btn btn-default submit"><i class="fa fa-paper-plane" aria-hidden="true"></i>  Send Message</button>
            </div>

        </div>
    </form>


    </div>
    </div>
</section>

</body>
</html>
